/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Balance = number;
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'userId' : UserId,
  'link' : string,
  'createdAt' : bigint,
  'quantity' : bigint,
  'serviceId' : ServiceId,
}
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export type PaymentMethod = { 'fiat' : null } |
  { 'crypto' : null };
export interface PaymentRequest {
  'id' : bigint,
  'paymentMethod' : PaymentMethod,
  'userId' : UserId,
  'approved' : boolean,
  'amount' : Balance,
  'transactionId' : string,
}
export interface Service {
  'id' : ServiceId,
  'pricePerThousand' : number,
  'active' : boolean,
  'name' : string,
  'minQty' : bigint,
  'maxQty' : bigint,
  'externalServiceId' : string,
}
export type ServiceId = bigint;
export type UserId = Principal;
export interface UserInfo { 'balance' : Balance, 'userId' : UserId }
export interface UserProfile { 'balance' : Balance }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFunds' : ActorMethod<[Balance, PaymentMethod, string], bigint>,
  'addService' : ActorMethod<
    [string, string, number, bigint, bigint],
    ServiceId
  >,
  'adjustBalance' : ActorMethod<[Principal, number], undefined>,
  'approvePayment' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  'getAllUsers' : ActorMethod<[], Array<UserInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[ServiceId, string, bigint], bigint>,
  'removeService' : ActorMethod<[ServiceId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateService' : ActorMethod<
    [ServiceId, string, string, number, bigint, bigint, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];