/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Balance = IDL.Float64;
export const PaymentMethod = IDL.Variant({
  'fiat' : IDL.Null,
  'crypto' : IDL.Null,
});
export const ServiceId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'userId' : UserId,
  'link' : IDL.Text,
  'createdAt' : IDL.Int,
  'quantity' : IDL.Nat,
  'serviceId' : ServiceId,
});
export const PaymentRequest = IDL.Record({
  'id' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'userId' : UserId,
  'approved' : IDL.Bool,
  'amount' : Balance,
  'transactionId' : IDL.Text,
});
export const UserInfo = IDL.Record({ 'balance' : Balance, 'userId' : UserId });
export const UserProfile = IDL.Record({ 'balance' : Balance });
export const Service = IDL.Record({
  'id' : ServiceId,
  'pricePerThousand' : IDL.Float64,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'minQty' : IDL.Nat,
  'maxQty' : IDL.Nat,
  'externalServiceId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFunds' : IDL.Func([Balance, PaymentMethod, IDL.Text], [IDL.Nat], []),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat],
      [ServiceId],
      [],
    ),
  'adjustBalance' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
  'approvePayment' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([ServiceId, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'removeService' : IDL.Func([ServiceId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateService' : IDL.Func(
      [ServiceId, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Balance = IDL.Float64;
  const PaymentMethod = IDL.Variant({ 'fiat' : IDL.Null, 'crypto' : IDL.Null });
  const ServiceId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'userId' : UserId,
    'link' : IDL.Text,
    'createdAt' : IDL.Int,
    'quantity' : IDL.Nat,
    'serviceId' : ServiceId,
  });
  const PaymentRequest = IDL.Record({
    'id' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'userId' : UserId,
    'approved' : IDL.Bool,
    'amount' : Balance,
    'transactionId' : IDL.Text,
  });
  const UserInfo = IDL.Record({ 'balance' : Balance, 'userId' : UserId });
  const UserProfile = IDL.Record({ 'balance' : Balance });
  const Service = IDL.Record({
    'id' : ServiceId,
    'pricePerThousand' : IDL.Float64,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'minQty' : IDL.Nat,
    'maxQty' : IDL.Nat,
    'externalServiceId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFunds' : IDL.Func([Balance, PaymentMethod, IDL.Text], [IDL.Nat], []),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat],
        [ServiceId],
        [],
      ),
    'adjustBalance' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
    'approvePayment' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(PaymentRequest)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([ServiceId, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'removeService' : IDL.Func([ServiceId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateService' : IDL.Func(
        [
          ServiceId,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };